/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Nikitos & 3130 (https://sketchfab.com/vrcityphoto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/extrasoundpro-e32364a157ac40a8a7ca6c4d1a95ef58
Title: EXTRASOUNDPRO
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame, useThree } from '@react-three/fiber';
import abc from '../assets/3d/extrasoundpro.glb';
import { a } from '@react-spring/three';


const Theme = (props) => {
  const tryRef = useRef()
  const { nodes, materials } = useGLTF(abc)
  return (
    <a.group ref={(tryRef)} {...props} >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[32124.293, 786590.188, -7111.346]}>
          <mesh
            
            
            geometry={nodes.Object_3.geometry}
            material={materials.baked_Global2}
          />
          <mesh
            
            
            geometry={nodes.Object_4.geometry}
            material={materials.baked_Global2}
          />
          <mesh
            
            
            geometry={nodes.Object_5.geometry}
            material={materials.baked_Global2}
          />
          <mesh
            
            
            geometry={nodes.Object_6.geometry}
            material={materials.baked_Global2}
          />
          <mesh
            
            
            geometry={nodes.Object_7.geometry}
            material={materials.baked_Global2}
          />
          <mesh
            
            
            geometry={nodes.Object_8.geometry}
            material={materials.baked_Global2}
          />
          <mesh
            
            
            geometry={nodes.Object_9.geometry}
            material={materials.baked_Global2}
          />
          <mesh
            
            
            geometry={nodes.Object_10.geometry}
            material={materials.baked_HROM}
          />
          <mesh
            
            
            geometry={nodes.Object_11.geometry}
            material={materials.baked_HROM}
          />
          <mesh
            
            
            geometry={nodes.Object_12.geometry}
            material={materials.baked_HROM}
          />
          <mesh
            
            
            geometry={nodes.Object_13.geometry}
            material={materials.baked_HROM}
          />
          <mesh
            
            
            geometry={nodes.Object_14.geometry}
            material={materials.baked_HROM}
          />
          <mesh
            
            
            geometry={nodes.Object_15.geometry}
            material={materials.baked_LEPNINA_biegeW}
          />
          <mesh
            
            
            geometry={nodes.Object_16.geometry}
            material={materials.baked_Material__311}
          />
          <mesh
            
            
            geometry={nodes.Object_17.geometry}
            material={materials.baked_stols}
          />
          <mesh
            
            
            geometry={nodes.Object_18.geometry}
            material={materials.wire_057008136}
          />
          <mesh
            
            
            geometry={nodes.Object_19.geometry}
            material={materials.wire_057008136}
          />
        </group>
      </group>
    </a.group>
  )
}

useGLTF.preload('/extrasoundpro.glb')

export default Theme;